export const REQUEST_QUESTIONS_PENDING = "REQUEST_QUESTIONS_PENDING";
export const REQUEST_QUESTIONS_SUCCESS = "REQUEST_QUESTIONS_SUCCESS";
export const REQUEST_QUESTIONS_FAILED = "REQUEST_QUESTIONS_FAILED";
export const REQUEST_QUESTIONS_UPDATE = "REQUEST_QUESTIONS_UPDATE";

export const GET_CURRENT_QUESTION = "GET_CURRENT_QUESTION";
export const GET_CURRENT_PENDING = "GET_CURRENT_PENDING";

export const GET_DESCRIPTION_STATUS = "GET_DESCRIPTION_STATUS";

export const GET_TEST_DATA = "GET_TEST_DATA";

export const CHANGE_SELECT_FIELD = "CHANGE_SELECT_FIELD";
